### ISSUE TITLE
Pillar to install java before zookeeper

### ISSUE THREAD

**Issue by estahn** [saltstack-formulas/zookeeper-formula#23]
It would be nice to have some sort of hook to install java before it goes ahead and installs zookeeper.

Example:

``` yml
zookeeper:
  require_java_sls: [sun-java, sun-java.env]
```

In `zookeeper.server` it will create the necessary includes and requirement statements.

Current workaround:

``` yml
include:
  - sun-java
  - sun-java.env

extend:
  zookeeper-service:
    service.running:
      - require:
        - sls: sun-java
        - sls: sun-java.env
```

Thoughts?
