### ISSUE TITLE
Zookeeper Install Warnings

### ISSUE THREAD

**Issue by paguilera** [saltstack-formulas/zookeeper-formula#42]
Saw this while installing in the `ID: install-zookeeper` section.
```
                        ID: install-zookeeper
                  Function: archive.extracted
                      Name: /usr/lib
                    Result: True
                   Comment: http://REDACTED/zookeeper-3.4.9.tar.gz extracted in /usr/lib/
                   Started: 13:18:13.584288
                  Duration: 1793.569 ms
                   Changes:   
                            ----------
                            directories_created:
                                - /usr/lib/
                                - /usr/lib/zookeeper-3.4.9/lib
                            extracted_files:
                                - zookeeper-3.4.9
                                - zookeeper-3.4.9/LICENSE.txt
                                - zookeeper-3.4.9/lib
                                - zookeeper-3.4.9/lib/log4j-1.2.16.LICENSE.txt
                                - zookeeper-3.4.9/lib/cobertura
                                - zookeeper-3.4.9/lib/cobertura/README.txt
                                - zookeeper-3.4.9/lib/jline-0.9.94.LICENSE.txt
                                - zookeeper-3.4.9/lib/jdiff
                                - zookeeper-3.4.9/lib/jdiff/zookeeper_3.4.9.xml
                                <SNIP>
                  Warnings: 'group' and 'user' are invalid keyword arguments for
                            'archive.extracted'. If you were trying to pass additional data to
                            be used in a template context, please populate 'context' with
                            'key: value' pairs. Your approach will work until Salt Carbon is
                            out. Please update your state files.

```
