### ISSUE TITLE
Custom user running zookeeper

### ISSUE THREAD

**Issue by nick-metz-fhe3** [saltstack-formulas/zookeeper-formula#57]
Hallo,

right now it is only possible to set a custom uid, but in our case we need a specific user + uid. I will add an merge request that allows to use an custom user. We keep zookeeper as default user, so there is no impact. We also should adjust the exapmle.pillar version 3.4.9, it is not in the repo anymore.

example pillar:
```
zookeeper:
  source_url: 'http://www.us.apache.org/dist/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz'
  version: 3.4.9
  source_md5: 3e8506075212c2d41030d874fcc9dcd2
  prefix: /usr/lib
  user: custom-user
  uid: 6030
  hosts_function: network.get_hostname
  hosts_target: 'roles:zookeeper'
  targeting_method: grain # [compound, glob] also supported
  config:
    data_dir: /var/lib/zookeeper/data
    port: 2181
    jmx_port: 2183
    snap_count: None
    snap_retain_count: 3
    purge_interval: None
    max_client_cnxns: None
    max_perm_size: 128
    max_heap_size: 1024
    initial_heap_size: 256
    jvm_opts: ''
    log_level: INFO
    quorum_port: 2888
    election_port: 3888
  restart_on_config: True
```
