### ISSUE TITLE
configuration for zookeeper-env.sh only work if process_control_system is disabled

### ISSUE THREAD

**Issue by nick-metz-fhe3** [saltstack-formulas/zookeeper-formula#61]
Hello,

right now it is only possible to configure zookeeper-env.sh if process_control_system is False. We should move the `file.managed` of zookeeper-env.sh outside of the if statement.

```
{%- if zk.process_control_system %}

  {%- if zk.restart_on_change %}

zookeeper-in-supervisord:
  cmd.run:
    - name: "{{ zk.pcs_restart_command }}"
    - require:
      - pkg: {{ zk.process_control_system_pkg }}
    - onchanges:
       - file: {{ zk.real_config }}/zoo.cfg

  {%- endif %}

{%- else %}

zookeeper-env.sh:
  file.managed:
    - name: {{ zk.real_config }}/zookeeper-env.sh
    - source: salt://zookeeper/templates/zookeeper-env.sh.j2
    - user: root
    - group: root
    - mode: 755
    - template: jinja
    - context:
      initial_heap_size: {{ zk.initial_heap_size }}
      java_home: "{{ zk.java_home }}"
      jmx_port: {{ zk.jmx_port }}
      jvm_opts: "{{ zk.jvm_opts }}"
      log_level: {{ zk.log_level }}
      max_heap_size: {{ zk.max_heap_size }}
      max_perm_size: {{ zk.max_perm_size }}

[..]
```
